esphome:
  name: servo
  friendly_name: servo

ota:
  - platform: esphome
    password: "REDACTED"

captive_portal:

esp32:
  board: esp32dev
  framework:
    #type: arduino
    type: esp-idf

mqtt:
  broker: !secret mqtt_host
  id: mqtt_client

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Uselessbox Fall Back"
    password: "STAs1li2612X"

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret homeassistant_api
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: useless_servo
            level: !lambda 'return level / 100.0;'

binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "Useless Switch"
    on_press:
      - delay: 50ms
      - servo.write:
          id: useless_servo
          level: -65%
      - delay: 1200ms
      - servo.write:
          id: useless_servo
          level: 100%


number:
  - platform: template
    name: Servo Control
    min_value: -60
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: useless_servo
            level: !lambda 'return x / 100.0;'

servo:
  - id: useless_servo
    output: pwm_output
    auto_detach_time: 3s

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO13
    frequency: 50 Hz

logger:

